Update CI/CD workflow to use yarn instead of npm

diff --git a/.github/workflows/build-and-push-to-docker-hub.yml b/.github/workflows/build-and-push-to-docker-hub.yml
--- a/.github/workflows/build-and-push-to-docker-hub.yml
+++ b/.github/workflows/build-and-push-to-docker-hub.yml
@@ -102,6 +102,7 @@ jobs:
                       export NVM_DIR=~/.nvm
                       source ~/.nvm/nvm.sh
                       npm --version
+                      yarn --version
                       echo "REPO_DIR_ON_SERVER: ${{ env.REPO_DIR_ON_SERVER }}"
                       pwd
                       if [ -d "${{ env.REPO_DIR_ON_SERVER }}" ]; then
@@ -114,6 +115,6 @@ jobs:
                       fi
                       cd ${{ env.REPO_DIR_ON_SERVER }} || { echo "Failed to change to directory"; exit 1; }
                       echo "${{ secrets.SERVER_SSH_ENV_FILE }}" > .env || { echo "Failed to create .env file"; exit 1; }
-                      git pull origin development || { echo "Failed to pull latest changes"; exit 1; }
-                      npm run get-logs || { echo "Failed to get logs"; }
-                      npm run update:prod || { echo "Failed to update production"; exit 1; }
+                      git pull origin update-ci-cd || { echo "Failed to pull latest changes"; exit 1; }
+                      yarn get-logs || { echo "Failed to get logs"; }
+                      yarn update:prod || { echo "Failed to update production"; exit 1; }
