Update CI/CD workflow and deployment process (#275)
* Update CI/CD workflow and deployment process

* Add support for all branches in CI/CD workflow

* Skip build image for testing

* Add setup step to set REPO_DIR_ON_SERVER environment variable

* Update deployment workflow to include setup step

* Update REPO_DIR_ON_SERVER in build-and-push-to-docker-hub.yml

* Update REPO_DIR_ON_SERVER path in build-and-push-to-docker-hub.yml

* Fix cloning logic in build-and-push-to-docker-hub.yml

* Update REPO_DIR_ON_SERVER in build-and-push-to-docker-hub.yml

* Add REPO_DIR_ON_SERVER environment variable

* Update REPO_DIR_ON_SERVER path in build-and-push-to-docker-hub.yml

* Add sudo su command to the deployment script

* Update REPO_DIR_ON_SERVER path in build-and-push-to-docker-hub.yml

* Update build-and-push-to-docker-hub.yml workflow

* Update REPO_DIR_ON_SERVER and add PATH to yarn command

* Add NVM setup and npm command to deployment script

* Add yarn get-logs command to build-and-push-to-docker-hub workflow

* Fix get-logs command in build script

* Update npm commands in build-and-push-to-docker-hub.yml

* Update CI/CD workflow to use yarn instead of npm

* Add yarn install step to CI/CD workflow

* Update production deployment in CI/CD workflow

* Add CURRENT_BRANCH environment variable to workflow

* Remove unnecessary pull_request branches from CI/CD workflow

diff --git a/.github/workflows/build-and-push-to-docker-hub.yml b/.github/workflows/build-and-push-to-docker-hub.yml
--- a/.github/workflows/build-and-push-to-docker-hub.yml
+++ b/.github/workflows/build-and-push-to-docker-hub.yml
@@ -1,4 +1,5 @@
-name: Build and Push Docker Images to Docker Hub
+name: Tech Cell Server CI/CD
+run-name: Tech Cell Server CI/CD
 
 on:
     push:
@@ -9,8 +10,7 @@ env:
     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
     COMPOSE_PROJECT_NAME: tech-cell-server
-    CURRENT_USER: 0:0
-    DOCKER_GROUP: 0
+    CURRENT_BRANCH: ${{ github.ref }}
 
 jobs:
     select-runner:
@@ -42,7 +42,7 @@ jobs:
                     echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
                   fi
 
-    build-and-push:
+    build-and-push-to-dockerhub:
         needs: select-runner
         runs-on: ${{ needs.select-runner.outputs.runner-label }}
 
@@ -79,3 +79,42 @@ jobs:
             - name: Remove .env file
               run: |
                   rm .env
+
+    deploy-to-server:
+        needs: [select-runner, build-and-push-to-dockerhub]
+        runs-on: ${{ needs.select-runner.outputs.runner-label }}
+
+        steps:
+            - name: Set REPO_DIR_ON_SERVER
+              run: echo "REPO_DIR_ON_SERVER=/home/${{ secrets.SERVER_SSH_USERNAME }}/tech-cell-server-ci-cd" >> $GITHUB_ENV
+
+            - name: Execute remote ssh commands
+              uses: appleboy/ssh-action@master
+              with:
+                  host: ${{ secrets.SERVER_SSH_HOST }}
+                  username: ${{ secrets.SERVER_SSH_USERNAME }}
+                  key: ${{ secrets.SERVER_SSH_KEY }}
+                  script: |
+                      export NVM_DIR=~/.nvm
+                      source ~/.nvm/nvm.sh
+                      npm --version
+                      yarn --version
+                      echo "REPO_DIR_ON_SERVER: ${{ env.REPO_DIR_ON_SERVER }}"
+                      pwd
+                      if [ -d "${{ env.REPO_DIR_ON_SERVER }}" ]; then
+                          if [ ! -d "${{ env.REPO_DIR_ON_SERVER }}/.git" ]; then
+                              rm -rf ${{ env.REPO_DIR_ON_SERVER }}
+                              git clone https://github.com/${{ github.repository }}.git ${{ env.REPO_DIR_ON_SERVER }} || { echo "Failed to clone repository"; exit 1; }
+                          fi
+                      else
+                          git clone https://github.com/${{ github.repository }}.git ${{ env.REPO_DIR_ON_SERVER }} || { echo "Failed to clone repository"; exit 1; }
+                      fi
+                      cd ${{ env.REPO_DIR_ON_SERVER }} || { echo "Failed to change to directory"; exit 1; }
+                      echo "${{ secrets.SERVER_SSH_ENV_FILE }}" > .env || { echo "Failed to create .env file"; exit 1; }
+                      git pull origin ${{ env.CURRENT_BRANCH }} || { echo "Failed to pull latest changes"; exit 1; }
+                      git switch ${{ env.CURRENT_BRANCH }} || { echo "Failed to switch to branch"; exit 1; }
+                      yarn install || { echo "Failed to install dependencies"; exit 1; }
+                      yarn get-logs || { echo "Failed to get logs"; }
+                      docker compose -f ./docker-compose.prod.yml pull || { echo "Failed to pull production"; exit 1; }
+                      docker compose -f ./docker-compose.prod.yml up -d || { echo "Failed to up production"; exit 1; }
+                      docker system prune -a -f || { echo "Failed to prune docker system"; exit 1; }
