Update CI/CD workflow to reset and pull latest changes

diff --git a/.github/workflows/tech-cell-server-ci-cd.yml b/.github/workflows/tech-cell-server-ci-cd.yml
--- a/.github/workflows/tech-cell-server-ci-cd.yml
+++ b/.github/workflows/tech-cell-server-ci-cd.yml
@@ -113,12 +113,14 @@ jobs:
                       cd ${{ steps.set_repo_dir.outputs.repo_dir_on_server }} || { echo "Failed to change to directory"; exit 1; }
                       echo "${{ secrets.SERVER_SSH_ENV_FILE }}" > .env || { echo "Failed to create .env file"; exit 1; }
 
+                      git reset --hard || { echo "Failed to reset hard"; exit 1; }
+                      git pull || { echo "Failed to pull latest changes"; exit 1; }
                       if [ "$(git rev-parse --abbrev-ref HEAD)" != "${{ steps.extract_branch.outputs.branch }}" ]; then
                         git switch ${{ steps.extract_branch.outputs.branch }} || { echo "Failed to switch to branch"; exit 1; }
                       fi    
 
                       git reset --hard || { echo "Failed to reset hard"; exit 1; }
-                      git pull origin ${{ steps.extract_branch.outputs.branch }} || { echo "Failed to pull latest changes"; exit 1; }
+                      git pull || { echo "Failed to pull latest changes"; exit 1; }
                       yarn install || { echo "Failed to install dependencies"; exit 1; }
                       yarn get-logs || { echo "Failed to get logs"; }
 
