fix(actions): :bug: fix issue creating .env file when CI/CD

diff --git a/.github/workflows/tech-cell-server-ci-cd.yml b/.github/workflows/tech-cell-server-ci-cd.yml
--- a/.github/workflows/tech-cell-server-ci-cd.yml
+++ b/.github/workflows/tech-cell-server-ci-cd.yml
@@ -359,7 +359,7 @@ jobs:
                       fi
 
                       cd ${{ steps.set_repo_dir.outputs.repo_dir_on_server }} || { echo "Failed to change to directory"; exit 1; }
-                      echo "${{ secrets.SERVER_SSH_ENV_FILE }}" > .env || { echo "Failed to create .env file"; exit 1; }
+                      echo "${{ secrets.SERVER_SSH_ENV_FILE }}" | base64 --decode > .env || { echo "Failed to create .env file"; exit 1; }
 
                       git reset --hard || { echo "Failed to reset hard"; exit 1; }
                       git pull || { echo "Failed to pull latest changes"; exit 1; }
